---
output:
  html_document: default
  pdf_document: default
---
# Домашнее задание № 1
## Работа с данными.
По адресу http://people.math.umass.edu/~anna/Stat597AFall2016/rnf6080.dat можно получить набор данных об осадках в Канаде с 1960 по 1980 годы. Необходимо загрузить эти данные при помощи ``read.table``. Воспользуйтесь справкой, чтобы изучить аргументы, которые принимает функция. 
- Загрузите данные в датафрейм, который назовите ``data.df``.

```{R}
data.df<-read.table("http://people.math.umass.edu/~anna/Stat597AFall2016/rnf6080.dat")
```

- Сколько строк и столбцов в ``data.df``? Если получилось не 5070 наблюдений 27 переменных, то проверяйте аргументы.

```{R}
#Количество строк:
data.df.nrow<-nrow(data.df)
#Количество столбцов:
data.df.ncol<-ncol(data.df)
#Количество строк:
data.df.nrow
#Количество столбцов:
data.df.ncol
```

- Получите имена колонок из ``data.df``.

```{R}
data.df.names<-names(data.df)
```

- Найдите значение из 5 строки седьмого столбца.

```{R}
variable<-data.df[7,5]
variable
```

- Напечатайте целиком 2 строку из ``data.df``

```{R}
data.df[2,]
```

- Объясните, что делает следующая строка кода ``names(data.df) <- c("year", "month", "day", seq(0,23))``. Воспользуйтесь функциями ``head`` и ``tail``, чтобы просмотреть таблицу. Что представляют собой последние 24 колонки?

```{R}
#Следующая строка кода, присвоит имена колонкам в датафрейме 
#(первым трем year, month, day соответственно, остальным номера от 0 до 23)
names(data.df) <- c("year", "month", "day", seq(0,23))
#Вызов ф-ии head - которая выводит имена колонок и несколько первых значений
head(data.df)
#Вызов ф-ии tail - которая выводит заголовки и последние несколько записей
tail(data.df)
```

- Добавьте новую колонку с названием *daily*, в которую запишите сумму крайних правых 24 колонок. Постройте гистограмму по этой колонке. Какие выводы можно сделать?

```{R}
for(i in seq(1,nrow(data.df))){
      data.df[i,28]<-sum(data.df[i,4:27])
   }
names(data.df)<-c("year", "month", "day", seq(0,23),"daily")
plot(data.df$daily)
```

По данной гистограмме видно, что в наборе данных присутствуют ошибочные значения, которые показывают, что количество осадков имеют отрицательные значения, что не может быть в природе. Из-за этих данных зависимость корректных данных невозможно оценить.

- Создайте новый датафрейм ``fixed.df`` в котром исправьте замеченную ошибку. Постройте новую гистограмму, поясните почему она более корректна.

```{R}
fixed.df<-data.df[data.df$daily>=0,]
plot(fixed.df$daily)
```

Данная гистаграмма более корректна, потому что все значения имеют положительные значения, поэтому разброс значений не такой большой, и следовательно, возможно анализировать полученные данные.

## Синтаксис и типизирование
* Для каждой строки кода поясните полученный результат, либо объясните почему она ошибочна.

```{R}
#Данные функции работают, не так как ожидалось, потому что они применяются не к списку числовых значений, а 
#к списку строк
v <- c("4", "8", "15", "16", "23", "42")
max(v)
#Функция max для строк определила максимальное значение строки исходя из лексиграфического порядка
#Соответственно, т.к. цифра "8" является самой большой цифрой, с которой начинаются строки, то она
#и является максимальной
sort(v)
#Функция сортировки также как и ф-ия "max" сравнивает строки исходя из лексиграфического порядка, 
#а при равном исходя из длины строки
###sum(v)     !!!!!Ошибка
#Предсказуемо, что ф-ия "sum" не работает, и ясно из ошибки, данная ф-ия не может складывать типы
#данных такие, как character
```

* Для следующих наборов команд поясните полученный результат, либо объясните почему они ошибочна.

```{R}
v2 <- c("5",7,12)
#v2[2] + 2[3]   !!!!!Ошибка
#В данном случае операция получение по индексу не может быть применена к типу данных numeric

df3 <- data.frame(z1="5",z2=7,z3=12)
df3[1,2] + df3[1,3]
#В данном случае ошибки не происходит, потому что вначале создается dataframe, в который записывается
#строка и два числа, а затем производится сложение двух чисел, при сложении df3[1,1] с любым из двух
#других элементов, получалась бы ошибка, т.к. типы складываемых переменных не совпадают и не могут быть сложены
l4 <- list(z1="6", z2=42, z3="49", z4=126)
l4[[2]] + l4[[4]]
#l4[2] + l4[4]    !!!!!Ошибка
#В данном примере в первом случае нет ошибки, потому что при обращении через двойные скобки возвращается
#элемент списка, а через одинарные-список с одним элементом, поэтому во втором случае происходит ошибка
```

## Работа с функциями и операторами
* Оператор двоеточие создаёт последовательность целых чисел по порядку. Этот оператор — частный случай функции ``seq()``, которую вы использовали раньше. Изучите эту функцию, вызвав команду ``?seq``. Испольуя полученные знания выведите на экран:
    1. Числа от 1 до 10000 с инкрементом 372. 
    1. Числа от 1 до 10000 длиной 50.
    
```{R}
#1)
seq(from=1,to=10000,by=372)
#2)
seq(from=1,to=10000,length.out = 50)
```

* Функция ``rep()`` повторяет переданный вектор указанное число раз. Объясните разницу между ``rep(1:5,times=3)`` и ``rep(1:5, each=3)``.

```{R}
rep(1:5,times=3)
rep(1:5, each=3)
```

Разница между двумя аргументами, передаваемыми в ф-ию ``rep()``, аргумент ``times`` повторяет переданный вектор,
указанное число раз, а аргумент ``each`` повторяет каждый элемент передаваемого вектора указанное число раз.

#Требования к оформлению
Работа должна быть выполнена на языке R Markdown в среде RStudio и сохранена в свой репозиторий в папку hw01.
Также требуется сохранить результат в виде PDF и отправить почтой для проверки.
Справку по установке и настройке R Markdown можно найти здесь http://rmarkdown.rstudio.com/
