**студент гр. РИ-450004 Захаров Вячеслав**

# Лабораторная работа 1 

Проверка следующих навыков: Манипулирование объектами данных; использование встроенных функций; 
построение простейших графиков; простейшие статистические концепции.

## Требования к оформлению
* Оформить решение в R Markdown. 
* Сохранить файл в свой репозиторий.
* Выгрузить R Markdown в HTML, назвать своим именем и отправить по почте (если хочется сдать раньше или нужна помощь).

## Исходные данные
Экспоненциальное распределение определяется следующей функцией распределения:
```
F(x) = 1 - e^(-λ⋅x)

```
Функция ``rexp`` генерирует случайные переменные при помощи экспоненциального распределения
``rexp(n=42, rate=5)`` вернёт 42 экспоненциально-распределённых числа с параметром (λ) равным 5. 
Ели второй аргумент не указан, будет использовано значение 1 т.е. получим "стандартное экспоненциальное распределение".

## Задание 1
1. Сгенерируйте 200 случайных значений из стандартного экспоненциального распределения и сохраните в вектор
_exp.1_. Найдите среднее и стандартное отклонение из данных этого вектора.
```{R}
exp.1<-rexp(n=200)
mean_exp.1<-mean(exp.1)#среднее
sd_exp.1<-sd(exp.1)#стандартное отклонение
lambda1<-1
result<-data.frame("параметр распределения"=lambda1,"Среднее значение"=mean_exp.1,"Стандартное отклонение"=sd_exp.1)#отображение данных
result
```
2. Повторите, использовав следующие значения параметра λ: 0.1, 0.5, 5, 10, и сохраните результаты в векторы: 
_exp.0.1_, _exp.0.5_, _exp.5_, _exp.10_.
```{R}
lambda_all<-c(0.1,0.5,5,10)
exp.01<-rexp(n=200,rate=lambda_all[1])
mean_exp.01<-mean(exp.01)#среднее
sd_exp.01<-sd(exp.01)#стандартное отклонение

exp.05<-rexp(n=200,rate=lambda_all[2])
mean_exp.05<-mean(exp.05)#среднее
sd_exp.05<-sd(exp.05)#стандартное отклонение

exp.5<-rexp(n=200,rate=lambda_all[3])
mean_exp.5<-mean(exp.5)#среднее
sd_exp.5<-sd(exp.5)#стандартное отклонение

exp.10<-rexp(n=200,rate=lambda_all[4])
mean_exp.10<-mean(exp.10)#среднее
sd_exp.10<-sd(exp.10)#стандартное отклонение

#сведем данные в общую таблицу
mean_exp_all<-c(mean_exp.01,mean_exp.05,mean_exp.5,mean_exp.10)
sd_exp_all<-c(sd_exp.01,sd_exp.05,sd_exp.5,sd_exp.10)

result<-data.frame("параметр распределения"=lambda_all,"Среднее значение"=mean_exp_all,"Стандартное отклонение"=sd_exp_all)#отображение данных
result
```

3. Функция ``plot()`` общая функция для визуализации данных. Функция ``hist()`` принимает данные и раскладывает 
их по корзинам. Чтобы использовать эти функции нужно для начала передать им данные, которые хотим визуализировать.
  1. Используйте функцию ``hist()`` для построения гистограммы полученного ранее стандартного распределения.
```{R}
hist(exp.1,breaks = 20,col = "lightgreen",
     xlab = "Значение из стандартного распределения",
     ylab="Частота",main = "Гистограмма стандартного экспоненциального распределения")
```
  
  **Краткий вывод по гистограмме:** Из гистограммы видно, что распределение имеет экспоненциальный вид,
  частота появлений значений наибольшая при малых значениях величин.
  
  2. Используйте функцию ``plot()`` с тем же самым вектором для построения графика значений в порядке следования.
```{R}
plot(exp.1,xlab = "Порядок следования",ylab = "Значение",main = "График стандартного экспоненциального распределения")
```
  
  **Краткий вывод по графику:** Из данного графика также видно, что большинство значений случайных переменных попало в область близкую к нулю. Так из графика видно, что основная часть значений попадает в область от 0 до 3 и лишь единичные значения выходят из этой области.
  
  3. Используйте функцию ``plot()`` с любыми двумя полученными ранее векторами, чтобы получить диаграмму рассеяния ([scatterplot](https://www.mathsisfun.com/data/scatter-xy-plots.html)) 
  этих векторов относительно друг друга.
```{R}
plot(exp.1,exp.5,xlab = "значения с lambda = 1",ylab = "значения с lambda = 5",main = "Диаграмма рассеяния вектора с лямбда, равной 1 и 5")
```

**Краткий вывод по гистограмме:** Из данной гистограмме также видно, что при различных значениях параметра распределения (λ) основная часть значений попадает в область ближе к нулю. Также из данного графика видно, что при увеличении λ область, в которую попадают значения сужается, что показывает зависимость данного вида распределения.

4. Теперь сравним свойства всех наших векторов. Для начала создадим вектор,
содержащий средние значения каждого из 5 полученных ранее распределений в порядке их создания.
Полученный вектор сохраним в переменную _exp.means_.
```{R}
exp.means<-c(mean_exp.1,mean_exp.01,mean_exp.05,mean_exp.5,mean_exp.10)
```

Далее необходимо создать следующие диаграммы рассеяния:
  1. Вектор с пятью средними относительно каждого из пяти векторов с различными значениями λ.
```{R}
lambda<-c(1,0.1,0.5,5,10)
plot(exp.means,lambda,xlab = "вектор средних значений",ylab = "lambda",main = "Диаграмма рассеяния средних значений отн-но лямбды")
```
  
  **Краткий вывод по гистограмме:** Из данной диаграммы видно что при уменьшении значения параметра распределения λ среднее значения вектора увеличивается, что показывает особенности данного распределения.
  
  2. Вектор с пятью стандартными отклонениями относительно каждого из пяти векторов с различными значениями λ.
```{R}
exp.sd<-c(sd_exp.1,sd_exp.01,sd_exp.05,sd_exp.5,sd_exp.10)
plot(exp.means,lambda,xlab = "вектор стандартных отклонений",ylab = "lambda",main = "Диаграмма рассеяния стандартных отклонений отн-но лямбды")
```
  
  **Краткий вывод по гистограмме:** Из данной диаграммы видно, что аналогично среднему значению, стандартное отклонение также имеет обратно-пропорциональное отношение к λ.
  
  3. Вектор с пятью средними относительно вектора с пятью стандартными отклонениями.
```{R}
plot(exp.means,exp.sd,xlab = "вектор средних значений",ylab = "вектор стандартных отклонений",main = "Диаграмма рассеяния ср. значений отн-но стандартных откл-ий")
```

**Краткий вывод по гистограмме:** Из данной диаграммы видно, что при увеличении средних значений при экспоненциальном распределении, вектор стандартных отклонений увеличивается практически линейно.

Для каждого графика, поясните увиденное.

## Задание 2
R достаточно производителен, чтобы вычислять относительно большие объёмы данных.
* Для демонстрации сгенерируйте 1100000 (1 млн. 100 тысяч) чисел из стандартного экспоненциального распределения и сохраните их в вектор _huge.exp.1_. Получите среднее и стандартное отклонение.
```{R}
huge.exp.1<-rexp(1100000)
mean_huge.exp.1<-mean(huge.exp.1)
sd_huge.exp.1<-sd(huge.exp.1)
mean_huge.exp.1
sd_huge.exp.1
```

* Получите гистограмму _huge.exp.1_. Она соответствует функции ``1 - e:^(-x)``? Должна ли?
```{R}
hist(huge.exp.1,breaks = 100,freq = FALSE,col = "lightgreen",
     xlab = "Значение из стандартного распределения",
     ylab="Плотность вероятности",main = "Гистограмма стандартного экспоненциального распределения")
x<-0:1100000
f<-1-exp(-x)
curve(1-exp(-x),from = 0,to=8,add=TRUE,col="blue")

```

**Краткий вывод по гистограмме:** Данная гистограмма не соответствует функции ``1 - e^(-x)``, но она и не должна ей соответствовать т.к. ф-ия F(x)=``1 - e^(-x)`` является функцией распределения и показывает, зависимость значения случайной величины от значения ф-ии при данном распределении. А данная гистограмма отображает зависимость плотности вероятности появления случайной частоты, которая имеет следующую зависимость ``f(x)=e^(-x)``.

* Получите среднее всех чисел из _huge.exp.1_ строго больших 1. Для проверки выборки может потребоваться новый вектор.
```{R}
more.one<-huge.exp.1[huge.exp.1>1]
mean(more.one)

```

* Получите матрицу _huge.exp.1.mat_, содержащую 1100 строк и 1000 колонок. Постройте гистограмму, использовав полученную матрицу.
Что можно сказать о полученных данных?
```{R}
huge.exp.1.mat<-matrix(data=huge.exp.1,nrow=1100,ncol=1000)
hist(huge.exp.1.mat,breaks = 100,freq = FALSE,col = "lightgreen",
     xlab = "Значение из стандартного распределения",
     ylab="Плотность вероятности",main = "Гистограмма с помощью матрицы")
```

**Краткий вывод по гистограмме:** Данная гистограмма получилась индентичная предыдущей, т.к. значения вектора и матрицы совпадают.

* Рассчитайте среднее 137-й колонки из _huge.exp.1.mat_.
```{R}
mean_huge.exp.1.mat<-mean(huge.exp.1.mat[,137])
mean_huge.exp.1.mat
```

* Найдите среднее всех 1000 колонок и сохраните их в вектор. Отобразите диаграмму средних зннчений колонок.
Объясните почему форма диаграммы отличается от виденных ранее.

```{R}
mean_huge.exp.1.mat.all<-apply(huge.exp.1.mat,2,mean)
plot(mean_huge.exp.1.mat.all,xlab="Элемент",ylab="Значение",main = "Диаграмма средних значений колонок")
```

**Краткий вывод по диаграмме:** Данная диаграмма имеет такой вид, потому что она отражает средние значения векторов экспоненциального распределения. Соответственно получилась усредненная выборка экспоненциального распределения и большинство значений этой выборки лежат около среднего значения всего вектора значений.

* Рассчитайте квадрат каждого значения из _huge.exp.1_ и найдите среднее и стандартное отклонение полученного вектора квадратов.
```{R}
square_huge.exp.1<-huge.exp.1^2
mean_square_huge.exp.1<-mean(square_huge.exp.1)
sd_square_huge.exp.1<-sd(square_huge.exp.1)
mean_square_huge.exp.1
sd_square_huge.exp.1
```
Объясните отличие от соответствующих показателей вектора _huge.exp.1_. Вам может помочь формула, по которой R рассчитывает
стандартное отклонение: ``sqrt(sum((x-mean(x))^2)/(n-1)) ``

**Краткий вывод:**Отличие значений объясняется тем, что при получении среднего значения и стандартного отклонения у вектора, каждое значение которого возведенно в квадрат, все значения увеличиваются. Поэтому разброс значений от среднего увеличивается, соответственно и среднее значение увеличивается, а при получении стандартного отклонения с помощью ф-ии _sd()_, которая расщитывает значение с помощью формулы описанной выше, разность квадратов будет значительно больше, чем простая разница значений, поэтому и стандартное отклонение вектора квадратов значений больше обычного вектора.