# Домашнее задание № 2
## Основы исследовательского анализа данных.
## Требования к оформлению
* Оформить решение в R Markdown. 
* Сохранить файл в свой репозиторий.
* Выгрузить R Markdown в HTML, назвать своим именем и отправить по почте (если хочется сдать раньше или нужна помощь).

## Исходные данные

По адресу https://raw.githubusercontent.com/SergeyMirvoda/da2016/master/data/calif_penn_2011.csv можно получить набор данных, 
содержащий информацию о домовладениях в Калифорнии и Пенсильвании за 2011г. Информация сгруппированна по зонам переписи ([Census tracts](https://en.wikipedia.org/wiki/Census_tract)).

>В построении диаграмм может помочь книга [The R Cookbook](http://shop.oreilly.com/product/9780596809164.do). Рецепты 10.1 и 10.2.

### Загрузка и очистка данных
- Загрузите данные в датафрейм, который назовите ``data``.

```{R}
data<-read.csv("https://raw.githubusercontent.com/SergeyMirvoda/da2016/master/data/calif_penn_2011.csv")
```
- Сколько строк и столбцов в ``data``?

```{R}
#Количество строк:
data.nrow<-nrow(data)
data.nrow
#Количество столбцов:
data.ncol<-ncol(data)
data.ncol
```

- Выполните следующую команду и объясните, что она делает.
```colSums(apply(data,c(1,2), is.na))```

```{R}
colSums(apply(data,c(1,2), is.na))
#colSums -ф-ия, кот-ая выводит количество значений TRUE для каждой колонки, данные значения получает ф-я apply 
#apply- ф-я, кот-ая применяет действие ф-ии is.na к набору данных data, и возвращает TRUE, в случае если ф-ия вернет TRUE
#ф-ия с(1,2), в данном случае показывает, что применяется ф-ия и к столбцам и к строкам
#is.na -ф-я, к-ая определяет какие значения отсутствуют или помечены как NA

#Проверить количество NA в колонке Renters можно с помощью следующей команды:
length(data$Renters[is.na(data$Renters)])
#Значения совпадают
```

- Функция ``na.omit()`` принимает датафрейм и возвращает новый датафрейм, игнорируя строки, содержащие
значение _NA_. Используйте эту функцию для удаления строк с неполными данными.

```{R}
data<-na.omit(data)
```

- Сколько строк было удалено?

```{R}
data.nrow-nrow(data)
```

- Соответствует ли результат выполнения, значениям из пункта 3?

```{R}
colSums(apply(data,c(1,2), is.na))
```

При проверке количества NA в данных с помощью команды, приведенной выше, видно, что все строки, содержащие значение
NA в какой-либо из колонок были очищены.

### Новые дома
* Переменная(колонка) _Built_2005_or_later_ содержит данные о проценте домов, построенных с 2005 года. Постройте диаграмму рассеяния (scatterplot)
медианы стоимости домов (переменная _Median_house_value_) относительно процента новых домов.

```{R}
plot(data$Median_house_value, data$Built_2005_or_later, xlab="медиана стоимости домов", ylab = "процент новых домов")
```

* Постройте ещё два графика для каждого из штатов отдельно. Номер штата содержится в переменной (_STATEFP_), где Калифорния 6-й штат, а Пенсильвания 42.

```{R}
plot(data$Median_house_value[data$STATEFP==6],data$Built_2005_or_later[data$STATEFP==6],xlab="медиана стоимости домов",ylab = "процент новых домов",main = "Штат Калифорния")

plot(data$Median_house_value[data$STATEFP==42],data$Built_2005_or_later[data$STATEFP==42],xlab="медиана стоимости домов",ylab = "процент новых домов",main = "Штат Пенсильвания")
```

### Незанятые дома
Уровень найма (vacancy rate) — доля домов, которые не были заняты. В данных содержатся колонки,
содержащие общее количество домовладений и количество не занятых домовладений. 

* В датафрейм _data_ добавьте новую колонку _vacancy_rate_, которая должна содержать вышеописанный показатель.

```{R}
#колонка total_units->общее количество домовладений
#колонка vacant_units-> свободные домовладения
data$vacancy_rate<-data$Vacant_units/data$Total_units
```

* Найдите минимум, максимум, среднее и медиану полученных значений показателя.

```{R}
#Минимум:
vacancy_rate.min<-min(data$vacancy_rate)
vacancy_rate.min
#Максимум:
vacancy_rate.max<-max(data$vacancy_rate)
vacancy_rate.max
#Медиана:
vacancy_rate.median<-median(data$vacancy_rate)
vacancy_rate.median
```

* Постройте диаграмму уровня найма относительно медианы стоимости домов. Что можно заметить?

```{R}
plot(data$vacancy_rate~data$Median_house_value, xlab="медиана стоимости домов", ylab="доля незанятых домов",main="Диаграмма рассеяния")
```

Из данной диаграммы видно, что уровень найма тем больше, чем меньше медиана стоимости домовладений.

### Корреляция
Колонка _COUNTYFP_ содержит числовой код округа внутри штата. Нас интересуют Butte County (округ 7 в Калифорнии), Santa Clara (округ 85 в Калифорнии) 
и York County (округ 133 в Пенсильвании).

* Объясните, что делает приведённый в конце задания код и как именно он это делает.

```{R}
acc <- c()
for (tract in 1:nrow(data)) {
  if (data$STATEFP[tract] == 6) {
    if (data$COUNTYFP[tract] == 1) {
      acc <- c(acc, tract)
    }
  }
}
accmv <- c()
for (tract in acc) {
  accmv <- c(accmv, data[tract,10])
}
median(accmv)
```

В приведенном выше коде вначале отбираются номера строк, со значением переменной _STATEFP_ = 6 и _COUNTYFP_ = 1, что соответствует округу №1 штату Калифорния. Данные номера записываются в переменную _acc_. Затем в следующем цикле в переменную _accmv_ записываются значения 10 столбца и номера строки из переменной, полученной на предыдущем шаге, из датафрейма _data_. Т.е. записываются соответствующие медианы стоимости домов.
В конце алгоритма берется медиана получившегося вектора значений.

* Напишите другим способом в одну строку, то же самое, что делает нижеуказанный код. Способов получить тот же ответ множество, достаточно одного.

```{R}
median(data$Median_house_value[data$STATEFP==6 & data$COUNTYFP==1])
```

* Найдите средний процент построенных домовладений в округах (Butte County, Santa Clara, York County)

```{R}
# процент построенных домов в Butte County (округ 7 в Калифорнии)
Butte_County.mean<-mean(data$Built_2005_or_later[data$STATEFP==6 & data$COUNTYFP==7])
Butte_County.mean
# процент построенных домов в Santa Clara (округ 85 в Калифорнии)
Santa_Clara.mean<-mean(data$Built_2005_or_later[data$STATEFP==6 & data$COUNTYFP==85])
Santa_Clara.mean
# процент построенных домов в York County (округ 133 в Пенсильвании)
York_County.mean<-mean(data$Built_2005_or_later[data$STATEFP==42 & data$COUNTYFP==133])
York_County.mean
```

* Функция ``cor`` рассчитывает коэффициент корреляции между двумя переменными. Рассчитайте корреляцию между
медианы стоимости домовладений (_Median_house_value_) и процентом построенных домов (_Built_2005_or_later_):
  1. для всего набора данных
  
```{R}
cor(data$Median_house_value, data$Built_2005_or_later)
```

  2. для Калифорнии
  
```{R}
cor(data$Median_house_value[data$STATEFP==6], data$Built_2005_or_later[data$STATEFP==6])
```

  3. для Пенсильвании
  
```{R}
cor(data$Median_house_value[data$STATEFP==42], data$Built_2005_or_later[data$STATEFP==42])
```

  4. для округа Butte County
  
```{R}
cor(data$Median_house_value[data$COUNTYFP==7], data$Built_2005_or_later[data$COUNTYFP==7])
```

  5. для округа Santa Clara

```{R}
cor(data$Median_house_value[data$COUNTYFP==85], data$Built_2005_or_later[data$COUNTYFP==85])
```

  6. для округа York County
  
```{R}
cor(data$Median_house_value[data$COUNTYFP==133], data$Built_2005_or_later[data$COUNTYFP==133])
```

* Постройте три диаграммы медианы стоимости домовладений (_Median_house_value_) относительно медианы дохода (_Median_household_income_) 
для трёх округов. Допустимо указать все три на одном графике.

```{R}
#Butte County
x1<-data$Median_house_value[data$COUNTYFP==7]
y1<-data$Median_household_income[data$COUNTYFP==7]
plot(x1, y1,type="p",col="red", xlab ="Стоимость домовладений", ylab = "Доход",main = "Округ Butte County")

#Santa Clara
x2<-data$Median_house_value[data$COUNTYFP==85]
y2<-data$Median_household_income[data$COUNTYFP==85]
plot(x2, y2,type="p",col="green", xlab ="Стоимость домовладений", ylab = "Доход",main = "Округ Santa Clara")

#округ York County
x3<-data$Median_house_value[data$COUNTYFP==133]
y3<-data$Median_household_income[data$COUNTYFP==133]
plot(x3,y3,type="p",col="blue", xlab ="Стоимость домовладений", ylab = "Доход",main = "Округ York County")
```



#### Код
```
acc <- c()
for (tract in 1:nrow(ca_pa)) {
  if (ca_pa$STATEFP[tract] == 6) {
    if (ca_pa$COUNTYFP[tract] == 1) {
      acc <- c(acc, tract)
    }
  }
}
accmv <- c()
for (tract in acc) {
  accmv <- c(accmv, ca_pa[tract,10])
}
median(accmv)
```