# Лабораторная работа 2
## Задачи для лабораторной: 
* манипулирование объектами данных;
* работа с циклами;
* переписывание существующего кода;
* моделирование при помощи генератора случайных величин.

## Требования к оформлению
* Оформить решение в R Markdown. 
* Сохранить файл в свой репозиторий.
* Выгрузить R Markdown в HTML, назвать своим именем и отправить по почте (если хочется сдать раньше или нужна помощь).

## Исходные данные
Установленная среда R включает в себя набор заранее сконфигурированных массивов данных.
В данной лабораторной требуется использовать одну из них  — датафрейм из 93 машин-новинок 1993 года.
Для того, чтобы загрузить данный датафрейм, необходимо выполнить следующие команды:

```
library(MASS)
data(Cars93)
```
Для того, чтобы ознакомиться со структурой и составом данных, можно выполнить команду ``View(Cars93)`` 
или нажать на соответствующую кнопку в RStudio.

### Задание 1
1. Выполните команду ``summary()`` на полном наборе данных. Можно ли по результату выполнения сказать сколько строк в датафрейме?
Если да, напишите сколько. Если нет, то приведите другой способ.
```{R}
library(MASS)
data(Cars93)
#View(Cars93)
summary(Cars93)
```

С помощью команды ``summary()`` можно просмотреть различные статистические показатели для каждой колонки, такие как *среднее значение*, *медиану*, *минимальное*, *максимальное* и т.д. для числовых показателей, а для номинальных переменных данная команда производит *классификацию*, показывая какое количество переменных относится к той или иной величине. Но эта команда не выводит количество строк. Зато если набор данных имеет колонку с номинальными значениями  (как в нашем случае колонка *Manufactures*) то по ней можно определить количество колонок, сложив все значения.

В нашем случае количество колонок будет равно **93**.

Для получения именно количества колонок можно воспользоваться командой ``nrow()``.
```{R}
#Количество колонок можно вывести с помощью команды nrom
nrow(Cars93)
```
2. Найдите среднюю цену машин с задним приводом.
```{R}
#т.к. данные хранятся в виде датафрейма, то чтобы получить данные конкретной колонки, нужно обратиться через знак $, также можно и с помощью квадратных скобок
#сначала выбираем все машины с задним приводом, потом их стоимости и берем от этих значений среднее:
mean.prices.rear<-mean(Cars93$Price[Cars93$DriveTrain=="Rear"])
mean.prices.rear
```
3. Найдите минимальное число лошадиных сил автомобиля для 7 пассажиров. Для 6 пассажиров.
```{R}
min.horsePower.7pass<-min(Cars93$Horsepower[Cars93$Passengers==7])
#минимальное количество лошадей для 7 пассажиров
min.horsePower.7pass
#минимальное количество лошадей для 6 пассажиров
min.horsePower.6pass<-min(Cars93$Horsepower[Cars93$Passengers==6])
min.horsePower.6pass
```
4. Найдите машины с максимальным, минимальным и средним(медианой) расстоянием, которая машина может проехать по трассе.
Вам понадобятся 2 колонки, чтобы рассчитать расстояние. Какие?


```{R}
#Для этого нам понадобятся колонки MPG.highway и Fuel.tank.capacity

max.distance<-max(Cars93$MPG.highway*Cars93$Fuel.tank.capacity)
min.distance<-min(Cars93$MPG.highway*Cars93$Fuel.tank.capacity)
median.distance<-median(Cars93$MPG.highway*Cars93$Fuel.tank.capacity)
statistics<-c(max.distance,min.distance,median.distance)
names(statistics)<-c("max","min","median")
statistics
#Получаем машину с максимальным расстоянием
headers<-c("Manufacturer","Model","MPG.highway","Fuel.tank.capacity")
cars.max.distance<-Cars93[Cars93$MPG.highway*Cars93$Fuel.tank.capacity==max.distance,headers]
cars.max.distance
#Получаем машину с минимальным расстоянием
cars.min.distance<-Cars93[Cars93$MPG.highway*Cars93$Fuel.tank.capacity==min.distance,headers]
cars.min.distance
#Получаем машину со средним(медиана) расстоянием
cars.median.distance<-Cars93[Cars93$MPG.highway*Cars93$Fuel.tank.capacity==median.distance,headers]
cars.median.distance
```
## Задание 2
В самом начале занятий приводился пример с фабрикой и производством автомобилей.
Ниже приведён пример кода, который старается оптимизировать выпуск продукции ориентируясь на доступные ресурсы.
```{R}
factory.run <- function (o.cars=1, o.trucks=1) {
  factory <- matrix(c(40,1,60,3),nrow=2, dimnames=list(c("трудодни","сталь"),c("автомобили","грузовики")))
  warehouse <- c(1600,70) #Доступно материалов на складе
  names(warehouse) <- rownames(factory)
  reserve <- c(8,1)
  names(reserve) <- rownames(factory)
  output <- c(o.cars, o.trucks)
  names(output) <- colnames(factory)
  steps <- 0 # Счётчик числа шагов цикла
  repeat {
    steps <- steps + 1
    needed <- factory %*% output # Подсчитаем ресурсы, которые нам нужны для производства требуемого кол-ва машин
    message(steps)
    print(needed)
    # Если ресурсов достаточно и остаток меньше или равен резерву, то мы произвели максимум возможного.
    # Нужно прекращать
    if (all(needed <= warehouse) && all((warehouse - needed) <= reserve)) {
      break()
    }
    # Если заявка слишком большая и ресурсов недостаточно, уменьшим её на 10%
    if (all(needed > warehouse)) {
      output <- output * 0.9
      next()
    }
    # Если всё наоброт, то увеличим на 10%
    if (all(needed < warehouse)) {
      output <- output * 1.1
      next()
    }
    # Если мы потребили одного ресурса слишком много, а другого недостаточно,
    # то увеличим план на случайную величину
    output <- output * (1+runif(length(output),min=-0.1,max=0.1))
  }
  
  return(output)
}
```
1. Выполните код и запустите эту функцию ``factory.run()``.
```{R}
#factory.run()
```

2. С каким входными значениями функция вызвана? Какой получился результат?

Функция вызвана с постоянными входными значениями _o.cars_=1, _o.trucks_=1

В результате получился ответ:

*трудодни*->1595.68640

*сталь*->69.30747

*автомобили*->10.47685

*грузовики*->19.61021

3. Повторите вызов 4 раза. Полученные ответы отличаются от полученных ранее? Если да, почему? Если нет, почему?
```{R}
#Полученные ответы
work.days<-c(1595.43412,1597.06742,1596.64979,1597.96666)
steel<-c(69.51973,69.84488,69.83509,69.86628)
cars<-c(10.25197,10.00849,9.997401,10.03206)
lorries<-c(19.75592,19.94546,19.945896,19.94474)
results<-data.frame("Трудодни"=work.days,"Сталь"=steel,"Автомобили"=cars,"Грузовики"=lorries)
results
```

Данные ответы отличаются, от полученных значений ранее, потому что при подборе значений, данная функция использовала случайные числа, она останавливалась когда значения попадут в необходимый диапазон значений.

4. В приведённом коде, переменные _steps_ и _output_ находятся внутри алгоритма.
Измените функцию так, чтобы она возвращала число шагов и произведённое количество машин.

```{R}
factory.run.modified.1 <- function (o.cars=1, o.trucks=1) {
  factory <- matrix(c(40,1,60,3),nrow=2, dimnames=list(c("трудодни","сталь"),c("автомобили","грузовики")))
  warehouse <- c(1600,70) #Доступно материалов на складе
  names(warehouse) <- rownames(factory)
  reserve <- c(8,1)
  names(reserve) <- rownames(factory)
  output <- c(o.cars, o.trucks)
  steps <- 0 # Счётчик числа шагов цикла
  repeat {
    steps <- steps + 1
    needed <- factory %*% output # Подсчитаем ресурсы, которые нам нужны для производства требуемого кол-ва машин
    # Если ресурсов достаточно и остаток меньше или равен резерву, то мы произвели максимум возможного.
    # Нужно прекращать
    if (all(needed <= warehouse) && all((warehouse - needed) <= reserve)) {
      break()
    }
    # Если заявка слишком большая и ресурсов недостаточно, уменьшим её на 10%
    if (all(needed > warehouse)) {
      output <- output * 0.9
      next()
    }
    # Если всё наоброт, то увеличим на 10%
    if (all(needed < warehouse)) {
      output <- output * 1.1
      next()
    }
    # Если мы потребили одного ресурса слишком много, а другого недостаточно,
    # то увеличим план на случайную величину
    output <- output * (1+runif(length(output),min=-0.1,max=0.1))
  }
  output<-c(output,steps)
  names(output) <- c(colnames(factory),"количество шагов")
  return(output)
}
```

5. Установите план равный тридцати автомобилям и 20 грузовикам и выполните функцию.

```{R}
factory.run.modified.2 <- function (o.cars=1, o.trucks=1) {
  factory <- matrix(c(40,1,60,3),nrow=2, dimnames=list(c("трудодни","сталь"),c("автомобили","грузовики")))
  warehouse <- c(2400,90) #Доступно материалов на складе
  names(warehouse) <- rownames(factory)
  reserve <- c(8,1)
  names(reserve) <- rownames(factory)
  output <- c(o.cars, o.trucks)
  
  needed <- factory %*% output
  
  steps <- 0 # Счётчик числа шагов цикла
  repeat {
    steps <- steps + 1
    needed <- factory %*% output # Подсчитаем ресурсы, которые нам нужны для производства требуемого кол-ва машин
    # Если ресурсов достаточно и остаток меньше или равен резерву, то мы произвели максимум возможного.
    # Нужно прекращать
    if (all(needed <= warehouse) && all((warehouse - needed) <= reserve)) {
      break()
    }
    # Если заявка слишком большая и ресурсов недостаточно, уменьшим её на 10%
    if (all(needed > warehouse)) {
      output <- output * 0.9
      next()
    }
    # Если всё наоброт, то увеличим на 10%
    if (all(needed < warehouse)) {
      output <- output * 1.1
      next()
    }
    # Если мы потребили одного ресурса слишком много, а другого недостаточно,
    # то увеличим план на случайную величину
    output <- output * (1+runif(length(output),min=-0.1,max=0.1))
  }
  output<-c(output,steps,needed)
  names(output) <- c(colnames(factory),"количество шагов",rownames(factory))
  return(output)
}
```
   1. Какой получили результат?
   2. Каким получился итоговый запрос ресурсов (переменная _needed_)
   3. Как много итераций пришлось пройти, чтобы получить ответ (переменная _steps_)? 
   4. Для подсчёта можно пользоваться функциями печати (``print``, ``message``) или вернуть результат из функции.
   
   Все полученные результаты были возвращены функцией в _data.frame_, который содержит данные о значениях переменных _output_, _steps_ и _needed_.
```{R}
#Результат
results<-factory.run.modified.2()
results
```
   