# Лабораторная работа 3
## Задачи для лабораторной: 
* работа с текстом;
* использование регулярных выражений для извлечения данных;
* переписывание существующего кода;
* ассиметричные распределения.

## Требования к оформлению
* Оформить решение в R Markdown. 
* Сохранить файл в свой репозиторий.
* Выгрузить R Markdown в HTML, назвать своим именем и отправить по почте (если хочется сдать раньше или нужна помощь).

## Исходные данные
Файл _forbes.htm_ содержит список богатейших американцев по версии журнала Форбс.
На его примере потренируемся в разборе html страниц.

### Задание 1
1. Используйте команду ``readLines`` для загрузки файла в текстовый вектор _html_.

```{R}
html<-readLines("../data/forbes.htm")
```
   1. Сколько строк в файле?
```{R}
length(html)
```
   
   2. Сколько символов в файле?
   
```{R}
#Функция nchar() подсчитывает количество символов в каждой строке
#Ф-ия sum() суммирует все значения
sum(nchar(html))
```
2. Откройте файл в текстовом редакторе. Найдите строки, содержащие данные о Билле Гейтсе и Ларри Эллисоне и запомните размер их дохода.

Размер дохода:

    1) Билла Гейтса составляет $72 000 000 000 ($72 B)
    2) Ларри Эллисон $41 000 000 000 ($41 B)

3. Напишите шаблон регулярного выражения и используйте функцию ``grep``, чтобы извлечь размер дохода из данных в векторе _html_.

```{R}
profits<-grep("\\$\\d+,*\\d*\\sB",html)
str(profits)
```

Удостоверьтесь, что полученный вектор номеров строк содержит содержит ровно 100 записей и ссылается на номера строк в котрых действительно есть
информация о доходе, а не просто первый попавшийся текст.

4. Напишите код, использовав регулярное выражение из п. 3, и функции ``regexp`` и ``regmatches``, чтобы извлечь все данные о доходе.

```{R}
m<-regexpr("\\$\\d+,*\\d*\\sB",html,perl=TRUE)
prof.regmatch<-regmatches(html,m)
```

Проверьте следующее:

   1. Должно быть ровно сто значений.
   
```{R}
length(prof.regmatch)
```

   2. Самый большой доход должен быть доход Билла Гейтса
   
```{R}
#т.к. Запись о Билл Гейтсе находится в списке первой
prof.regmatch[1]
```

   3. Такой доход должен быть в списке один раз.
   
```{R}
#произведем выбор по условию равенства
length(prof.regmatch[prof.regmatch==prof.regmatch[1]])
```

   4. В всписке должна быть цифра, которую мы запомнили для Ларри Эллисона.
   
```{R}
#Доход Ларри Эллисона $41 B
prof.regmatch[prof.regmatch=="$41 B"]
```

   5. Должно быть как минимум два значения, встречающихся несколько раз.
   
```{R}
length(unique(prof.regmatch))
```

Т.к. всего список состоит из 100 записей, а уникальных только 66, соответственно неуникальных 34 значения

### Задание 2
5. В данных доход представлен в формате **"$42 B"**, что означает **42 × 10^9**.
Преобразуйте этот формат в числовой и сохраните в вектор _worths_.

```{R}
worths<-as.numeric(sub(",",".",sub(" B","",sub("\\$","",prof.regmatch))))
worths<-worths*10^9
```

Удостоверьтесь в следующем:
   1. _worths_ является вектором и в нём сто занчений типа _double_.
   
```{R}
typeof(worths) #ф-ия для определения типа данных
length(worths)
```

   2. Все элементы вектора _worths_ больше 1 миллиарда.

```{R}
length(worths[worths>1*10^9])
```

   3. Самое большое число это доход Билла Гейтса.
   
```{R}
#Доход Билла Гейтса 72*10^9 $
length(worths[worths>72*10^9])
```

6. Используйте вектор _worths_ , чтобы выяснить следующее:

   1. Какова медиана ста этих записей?
   
```{R}
median.worths<-median(worths)
median.worths
```

   2. Средний доход?
   
```{R}
mean.worths<-mean(worths)
mean.worths
```

   3. Как много людей из этого списка имеют доход больше 5млрд., 10, 25?
   
```{R}
statistic<-data.frame("больше 5 млрд."=length(worths[worths>5*10^9]),
                      "больше 10 млрд."=length(worths[worths>10*10^9]),
                      "больше 25 млрд."=length(worths[worths>25*10^9]),
                      "медиана"=median.worths,
                      "среднее"=mean.worths)
statistic
```   

    1. Какой их общий доход?

```{R}
sum(worths[worths>5*10^9])
```

    2. Какую долю от общего дохода, составляет пятёрка самых богатых.

```{R}
share.5.most.worths<-sum(worths[1:5])/sum(worths)
share.5.most.worths
```

    3. Какую долю от общего дохода, составляют 20 самых богатых.
```{R}
share.20.most.worths<-sum(worths[1:20])/sum(worths)
share.20.most.worths
```

   4. В данных [федерального резерва США](https://www.federalreserve.gov/releases/z1/current/z1.pdf) найдите
   показатель дохода всех домохозяйств (Household net worth) в соответвующем году, какую долю
   общего дохода составляют 100 богатейших людей.
   
```{R}
#Данные в файле forbes.htm приведены за 2013 год
#Показатель дохода всех домохозяйств США за 2013 год составил: 81,396*10^12 $
sum(worths)/(81.396*10^12)
```

100 богатейших людей составляют около 1.6% от всего дохода всех домохозяйств США